update GARDEN_PLANTS.FRUITS.FRUIT_DETAILS
set fruit_name = 'banana', root_depth = 'D'
where fruit_name = 'apricot';

-- Time Travel を使って UPDATE 前の状態に復元
-- 方法: BEFORE(STATEMENT => '<query_id>') を使用

-- Step 1: UPDATE の QUERY_ID を取得
SELECT QUERY_ID, QUERY_TEXT, START_TIME
FROM TABLE(GARDEN_PLANTS.INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE QUERY_TEXT ILIKE '%update%FRUIT_DETAILS%'
ORDER BY START_TIME DESC
LIMIT 5;

-- Step 2: UPDATE 前のデータを確認（<query_id> を実際のIDに置き換え）
SELECT *
FROM GARDEN_PLANTS.FRUITS.FRUIT_DETAILS
BEFORE(STATEMENT => '01c36ff1-0000-e32b-0001-2512000836e6');

-- Step 3: テーブルを UPDATE 前の状態に復元
CREATE OR REPLACE TABLE GARDEN_PLANTS.FRUITS.FRUIT_DETAILS
AS
SELECT *GARDEN_PLANTS.FRUITS.FRUIT_DETAILS
FROM GARDEN_PLANTS.FRUITS.FRUIT_DETAILS
BEFORE(STATEMENT => '01c36ff1-0000-e32b-0001-2512000836e6');
