list @ZENAS_ATHLEISURE_DB.PRODUCTS.PRODUCT_METADATA;

select $1
from @ZENAS_ATHLEISURE_DB.PRODUCTS.PRODUCT_METADATA;

select $1
from @ZENAS_ATHLEISURE_DB.PRODUCTS.PRODUCT_METADATA/swt_product_line.txt;